### ISSUE TITLE
More context around gem upgrades

### ISSUE THREAD

**Issue by jasnow** [librariesio/lib2issues#4]
First mentioned in this issue: https://github.com/24pullrequests/24pullrequests/issues/964:
- If these type of issues are auto generated by libraries.io, I suggest adding some more context (words), sure as
  - "You have a new version of gem https://libraries.io/rubygems/nokogiri/1.6.7.rc4" or
  - "Libraries.io has found that you have a new version of gem https://libraries.io/rubygems/nokogiri/1.6.7.rc4"

**Comment by andrew** [comment]
@jasnow improved the body of the issue here: https://github.com/librariesio/lib2issues/commit/c73e74b206a5114fdbc24e0e0b0cd0becdae0d7f
