### ISSUE TITLE
Maybe not report gem if the current version greater than newer version

### ISSUE THREAD

**Issue by jasnow** [librariesio/lib2issues#7]
Maybe not report gem if the current version > newer version.
- Example: 24pr version is 1.2.2 > newer version is 0.3.46.
  - https://github.com/24pullrequests/24pullrequests/issues/1021

**Comment by andrew** [comment]
@jasnow I've just added a check for it here: https://github.com/librariesio/lib2issues/commit/a3d1e615e83fc3155f1f94f678d7a02fdd4f3c95 and deployed it, will see if it works soon!

**Comment by jasnow** [comment]
OK
